### ISSUE TITLE
Android app says, Invalid URL

### ISSUE THREAD

**Issue by MShirazAhmad** [suxSx/TRAWO#2]
I have installed everything as per the directions. API is also working. But the android app says URL is invalid. 
I set up a separate server on domainname.com directly. Apache2 folder path includes the core [folder.](url) [](URL)

[https://lh5.googleusercontent.com/Yv3THGuAwP5avJ8FWadr7YZUS485ZuQLH7GaSGwJG9vy1-9EzwUyBPu3sOGflOWkj6N5dVTYVHM12aEAR46c7k1rSW2Xe4TVw8F32H_N20gozOj_nUpVhU9VtqV67muAnpceBHmN](https://lh5.googleusercontent.com/Yv3THGuAwP5avJ8FWadr7YZUS485ZuQLH7GaSGwJG9vy1-9EzwUyBPu3sOGflOWkj6N5dVTYVHM12aEAR46c7k1rSW2Xe4TVw8F32H_N20gozOj_nUpVhU9VtqV67muAnpceBHmN)

**Comment by NorseByte** [comment]
Hi, you need to enter the complete url address. Let's say you put the core files in a folder named **core**. The url should then be **http://t.shiraz-ahmad/core** also rember to check if the server uses https or http. Did this  fix it?

**Comment by NorseByte** [comment]
To check if the app is not responding can you use the url https://knoph.cc/footer it should say that the url is valid but wrong token.

**Comment by MShirazAhmad** [comment]
This link (https://knoph.cc/footer
<https://mailtrack.io/trace/link/fa792845a53b8d2c655932fa859172158d8e65ca?url=https%3A%2F%2Fknoph.cc%2Ffooter&userId=5034341&signature=e1ad1cb4a27e0291>)
works fine.

my core folder is hosted on the following URL: *http://t.shiraz-ahmad/
<http://t.shiraz-ahmad/>*
*You can test by yourself using the following link **http://t.shiraz-ahmad.com
<https://mailtrack.io/trace/link/ec4cdbe4bfeb4fbfdcf3e1938bef30338a0734f9?url=http%3A%2F%2Ft.shiraz-ahmad.com&userId=5034341&signature=dfae255a0265985f>*
\?token=b2c73d4f013922ae7e3fa41aac92238e&subject=subject&=addr=addr
URL is operational but app is not accepting it. It is hosted on port 80
(http)
[image: image.png]


Shiraz

**Comment by MShirazAhmad** [comment]
Issue resolved. Thanks.
It was not working with HTTP, but after installing SSL and switching it on HTTPS, it started working.
Thanks

**Comment by NorseByte** [comment]
Great that it worked out for you. Nice to know that it has an glitch when it comes to http/https. Thanks for the update, I will make an update later on addressing this issue.

**Comment by NorseByte** [comment]
Update needed for app fetch request using http and https.
