### ISSUE TITLE
Gmail 

### ISSUE THREAD

**Issue by MShirazAhmad** [suxSx/TRAWO#3]
At the end of the HTML email, I added the following code:
```
<p><img style="display: none!important;" src="https://t.shiraz-ahmad.com/?image=vdxtn" width="1" height="1" /></p>

```
And sent it to my Gmail account from the outlook account. 
On receiving the end of my Gmail account, when I opened the email to see if the tracker registers my email opened, It does register my opened event. But, instead of showing the email reader IP and his details, the TRAWO app showed the following log details:

> 66.249.93.106
> 2021-07-0715: 13: 31
> Country: United States. Region: California. City: Mountain View. ISP: Google LLC. ORG: Google LLC. AS: AS15169 Google LLC.
> windows:Mozilla Firefox:Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GooglelmageProxy)

On further inspection, I noticed, my tracking code was changed to the following (in gmail):
```
<p><img style="display:none!important" src="https://ci6.googleusercontent.com/proxy/r_47XIOspnRkRoOOj7s_ryPQ8dkHBIJ7cKXCr5i9UubH4cSdgpHe2J8Hn5yLx_kEMzOKtsdP_BKnvw=s0-d-e1-ft#https://t.shiraz-ahmad.com/?image=5lxyb" width="1" height="1" class="CToWUd"></p>

```
From this experiment, I concluded that the location/IP of the emails sent to Gmail accounts can not be traced, because google adds a proxy layer on our tracking link. Although, email opens work perfectly. 

I took the experiment one step ahead by sending an email to the outlook account. Email opened on the outlook account worked perfectly, and the correct location/IP was registered as well.

I found reference as well https://sendloop.com/articles/the-effect-of-gmail-image-proxy-to-email-marketers/

**Comment by NorseByte** [comment]
Hi! This is half correct and half incorrect. It completely depends on the end user.

The Image loads when the user opens the mail, so you will still be capable to see when it is displayed, witch is most of the point for this app. In addition, if the end user utilizes programs like outlook. The email will then be loaded local on the machine and you will then get another IP witch is different from the one on the online Gmail folder.
