### ISSUE TITLE
Creating Tracker from Post -- 'Tracker Category' Parameter

### ISSUE THREAD

**Issue by MShirazAhmad** [suxSx/TRAWO#4]
In documentation, following is given:

> **To create a tracker from POST**:
> ```python
> {URL-ADDR}\core\?token={YOUR-TOKEN}&subject={SUBJECT}&=addr={TO-EMAIL}
> ```
> This will give the following out put:
> ```python
> {"tracker":"{TRACKER-ID}"}
> `

What parameter should I add to define 'Tracker Catagory' (pdf or image or other) as well for creating parameter from post?

**Comment by NorseByte** [comment]
Hi, the tracker category are hard coded for the moment into the core. Look at the [def.php](https://github.com/suxSx/TRAWO/blob/main/core/def.php).

Here will you find the values:

```
$file_list = array(
  '1' => "email",
  '2' => "pdf",
  '3' => "docx",
  '4' => "other"
);
```

You can change or add values here as you like. For the moement it dosent have any other function than to catogrise the trackers.  The value are then saved as text into the mySQL db on the server. So when you retrive the data you get the type in plain text. 


### Using JSON simply use the **file** tag:
```
$jsonPost = array(
    'task' => 'createtracker',
    'token' => '{YOUR-TOKEN}',
    'addr' => '{TO-ADDR}',
    'subject' => '{SUBJECT}',
    'file' => '{FILE/EMAIL/DOC/PDF}',
);
```

### Using the php provider add **file** here as well:
`{URL-ADDR}\core\?token={YOUR-TOKEN}&subject={SUBJECT}&=addr={TO-EMAIL}&file={1/2/3/4}`

But here you use the number form the file array that are hardcoded into the index file.

**Comment by MShirazAhmad** [comment]
Many thanks.
