### ISSUE TITLE
Cannot setup

### ISSUE THREAD

**Issue by robotfx** [suxSx/TRAWO#5]
Cannot pass the create user process. I always get a time-out error. DB created successfully though., only the user cannot.

I'm on Raspberry Pi4, Nginx and MariaDB. Maybe the script needs some php extensions enabled that I don't have? What are the requests?

**Comment by robotfx** [comment]
appears to have been some php limits regarding the max chjildren. It's working now

**Comment by NorseByte** [comment]
Great, thanks for the update.
